import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import { HomeBanner } from '../features/app/components';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <HomeBanner />
      <Link href="/about">About</Link>
    </div>
  );
};

export default Home;
